[package]
name = "rialo-edge-log-proof"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []
implementation = []

[dependencies]
rialo-venus = "0.18.1"
rialo-venus-proc-macro = "0.18.1"
rialo-s-program = "0.18.1"

serde = { version = "1.0.219", features = ["derive"] }
bincode = "1.3.3"

